### ISSUE TITLE
juju 2.0rc1 to deploy openstack components into xenial controller's lxd

### ISSUE THREAD

**Issue by chz8494** [canonical/jujucharms.com#352]
Hi Guys, 

I'm trying to put openstack components into lxd container. Apparently the container needs to have networking pre-setup and this was used to be taken cared by using lxc's /usr/share/lxc/config/xxx in trusty. However I noticed that in the new xenial, lxd manages lxc settings, and seems a lxc profile defines everything now.
The steps I did and led to problem:
1. put "lxc profile device set default eth0 parent juju-br0" in my yaml stage1 and run it for host preparation.
1. juju ssh into hosts to check the default profile is using my bridge juju-br0 instead of default lxdbr0 
2. run stage2 yaml bundle to start deploying openstack service components.
and then the problem comes.
For some reason juju will always overwrite my predefined profile and uses lxdbr0...
Is it a bug or any options I missed? I checked lxd charms and its options, didn't see anything about defining lxc profile.

**Comment by chz8494** [comment]
series: xenial
  services:
    controller-node:
      charm: ./trusty/ubuntu-controller
      num_units: 3
      constraints: tags=controller
    compute-node:
      charm: ./trusty/ubuntu-compute
      num_units: 2
      constraints: tags=compute
    ntp:
      charm: ./xenial/ntp
      options:
        source: '192.168.100.2'
        auto_peers: true
  overrides:
    ceph-public-network: 192.168.5.0/24
    ceph-cluster-network: 192.168.4.0/24
    use-syslog: true
    syslog_rotate: 90
    messages_rotate: 12
    nova_logs: true
    protocol: relp
    openstack-origin: distro
    use-syslog: true
    os-admin-network: 192.168.100.0/24
    os-internal-network: 192.168.8.0/24
    os-public-network: 192.168.7.0/24
    os-data-network: 192.168.6.0/24

  services:
    ceph-mon:
      charm: ./xenial/ceph-mon
      num_units: 3
      to:
        - controller-node/0
        - controller-node/1
        - controller-node/2
      options:
        fsid: xxx
        monitor-secret: xxx
    ceph-osd:
      charm: ./xenial/ceph-osd
      num_units: 2
      to:
        - compute-node/0
        - compute-node/1

```
  options:
    osd-devices: /dev/sda /dev/sdb /dev/sdc /dev/sdd
    osd-journal: /dev/sde /dev/sdf
    osd-journal-size: 1024
    osd-reformat: 'yes'

  charm: ./xenial/nova-cloud-controller
  num_units: 3
  to:
    - lxd:controller-node/0
    - lxd:controller-node/1
    - lxd:controller-node/2
  options:
    vip: 192.168.100.24 192.168.8.24 192.168.7.24
    network-manager: Neutron
    service-guard: true
    console-access-protocol: vnc
    console-proxy-ip: 192.168.100.24
    single-nova-consoleauth: false
```
